export const cheatSheetLabels: Record<string, string> = {
  bg: 'Пищови',
  bn: 'চিট শিট',
  cn: '速查表',
  de: 'Spickzettel',
  es: 'Hojas de referencia',
  fa: 'برگه‌های تقلب',
  fr: 'Aide-mémoire',
  he: 'דפי עזר',
  hi: 'चीट शीट',
  id: 'Contekan',
  it: 'Schede rapide',
  ja: 'チートシート',
  kh: 'សន្លឹកជំនួយ',
  kk: 'Шпаргалкалар',
  ko: '치트시트',
  mr: 'चीट शीट',
  nl: 'Cheatsheets',
  pl: 'Ściągawki',
  ptbr: 'Folhas de referência',
  ru: 'Шпаргалки',
  th: 'ชีทสรุป',
  tr: 'Kopya kağıtları',
  tw: '速查表',
  uk: 'Шпаргалки',
  ur: 'چیٹ شیٹس',
  uz: 'Shpargalkalar',
  vi: 'Tài liệu tóm tắt',
}
